version: '2.2'

services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

